#!/usr/bin/env ansible-playbook

---
- name: Install Tomcat 
  hosts: "{{env}}"
  become: yes
  become_user: root
  vars_files:
        - "inventory/{{env}}_vars.yml"
  tasks:
        - include: tasks/setuptomcat.yml
