- name: Copy artifact bar
  copy: src={{artifact}} dest=/opt/tomcat/webapps/ mode=755 group=tomcat owner=tomcat mode=755

- name: start tomcat server
  command: "./init.sh start" 
  args:
    chdir: /opt/tomcat/bin/
  #command: sudo /bin/sh /opt/tomcat/bin/startup.sh
  sudo: true
  #become: yes
  #become_user: tomcat
  #become_method: sudo
