# Create ec2 instance
- name: 1. Launch instance
  ec2: keypair={{keypair}} group={{security_group}}
       instance_type={{instance_type}} image={{image}} region={{region}}
       wait=true count=1
  register: ec2

# Add instance public IP to a new hostgroup for use in the next play.
- name: 2. Add new instances to host group
  add_host: hostname={{item.public_ip}} groupname=apphosts
  with_items: "{{ec2.instances}}"

- name: 3. Wait for the instances to boot by checking the ssh port
  wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
  with_items: "{{ec2.instances}}"

- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile dest="inventory/hosts" insertafter=[{{env}}] line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
     tags:
       Name: tomcat
