- name: 1. run tests on application
  action: uri url=http://localhost:8080/CounterWebApp return_content=yes
  register: webpage

- fail: msg='application is not running'
  when: "'Hello World' not in webpage.content"

- name: print to stdout
  command: curl http://169.254.169.254/latest/meta-data/public-hostname
  register: ec2

- debug: msg="Check out application here http://{{ec2.stdout}}:8080/CounterWebApp"
